import type { Metadata } from 'next';
import { Rubik, Poppins } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';

import { cn } from '@/lib/utils';
import Providers from '@/components/Providers';
import { Toaster } from '@/components/ui/toaster';

const rubik = Rubik({ subsets: ['latin'] });
const poppins = Poppins({ weight:['200','400','600'] ,subsets:['latin']});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body
				className={cn('min-h-screen antialiased', poppins.className)}>
				<Providers>
					{children}
					<Toaster />
				</Providers>
			</body>
		</html>
	);
}
